// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/schema/types/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KeyDescriptor struct {
	Name        string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Store       string                `protobuf:"bytes,4,opt,name=store,proto3" json:"store,omitempty"`
	Prefix      []byte                `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Parts       []*KeyDescriptor_Part `protobuf:"bytes,6,rep,name=parts,proto3" json:"parts,omitempty"`
	ValueType   string                `protobuf:"bytes,7,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
}

func (m *KeyDescriptor) Reset()         { *m = KeyDescriptor{} }
func (m *KeyDescriptor) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor) ProtoMessage()    {}
func (*KeyDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_335ca074c797b8b4, []int{0}
}
func (m *KeyDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor.Merge(m, src)
}
func (m *KeyDescriptor) XXX_Size() int {
	return m.Size()
}
func (m *KeyDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor proto.InternalMessageInfo

func (m *KeyDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyDescriptor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *KeyDescriptor) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *KeyDescriptor) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *KeyDescriptor) GetParts() []*KeyDescriptor_Part {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *KeyDescriptor) GetValueType() string {
	if m != nil {
		return m.ValueType
	}
	return ""
}

type KeyDescriptor_Part struct {
	// Types that are valid to be assigned to Sum:
	//	*KeyDescriptor_Part_Bytes_
	//	*KeyDescriptor_Part_String_
	//	*KeyDescriptor_Part_Separator_
	Sum isKeyDescriptor_Part_Sum `protobuf_oneof:"sum"`
}

func (m *KeyDescriptor_Part) Reset()         { *m = KeyDescriptor_Part{} }
func (m *KeyDescriptor_Part) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor_Part) ProtoMessage()    {}
func (*KeyDescriptor_Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_335ca074c797b8b4, []int{0, 0}
}
func (m *KeyDescriptor_Part) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDescriptor_Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDescriptor_Part.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDescriptor_Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor_Part.Merge(m, src)
}
func (m *KeyDescriptor_Part) XXX_Size() int {
	return m.Size()
}
func (m *KeyDescriptor_Part) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor_Part.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor_Part proto.InternalMessageInfo

type isKeyDescriptor_Part_Sum interface {
	isKeyDescriptor_Part_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type KeyDescriptor_Part_Bytes_ struct {
	Bytes *KeyDescriptor_Part_Bytes `protobuf:"bytes,1,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
}
type KeyDescriptor_Part_String_ struct {
	String_ *KeyDescriptor_Part_String `protobuf:"bytes,2,opt,name=string,proto3,oneof" json:"string,omitempty"`
}
type KeyDescriptor_Part_Separator_ struct {
	Separator *KeyDescriptor_Part_Separator `protobuf:"bytes,3,opt,name=separator,proto3,oneof" json:"separator,omitempty"`
}

func (*KeyDescriptor_Part_Bytes_) isKeyDescriptor_Part_Sum()     {}
func (*KeyDescriptor_Part_String_) isKeyDescriptor_Part_Sum()    {}
func (*KeyDescriptor_Part_Separator_) isKeyDescriptor_Part_Sum() {}

func (m *KeyDescriptor_Part) GetSum() isKeyDescriptor_Part_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *KeyDescriptor_Part) GetBytes() *KeyDescriptor_Part_Bytes {
	if x, ok := m.GetSum().(*KeyDescriptor_Part_Bytes_); ok {
		return x.Bytes
	}
	return nil
}

func (m *KeyDescriptor_Part) GetString_() *KeyDescriptor_Part_String {
	if x, ok := m.GetSum().(*KeyDescriptor_Part_String_); ok {
		return x.String_
	}
	return nil
}

func (m *KeyDescriptor_Part) GetSeparator() *KeyDescriptor_Part_Separator {
	if x, ok := m.GetSum().(*KeyDescriptor_Part_Separator_); ok {
		return x.Separator
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*KeyDescriptor_Part) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*KeyDescriptor_Part_Bytes_)(nil),
		(*KeyDescriptor_Part_String_)(nil),
		(*KeyDescriptor_Part_Separator_)(nil),
	}
}

type KeyDescriptor_Part_Bytes struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FixedWidth  uint32 `protobuf:"varint,3,opt,name=fixed_width,json=fixedWidth,proto3" json:"fixed_width,omitempty"`
}

func (m *KeyDescriptor_Part_Bytes) Reset()         { *m = KeyDescriptor_Part_Bytes{} }
func (m *KeyDescriptor_Part_Bytes) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor_Part_Bytes) ProtoMessage()    {}
func (*KeyDescriptor_Part_Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_335ca074c797b8b4, []int{0, 0, 0}
}
func (m *KeyDescriptor_Part_Bytes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDescriptor_Part_Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDescriptor_Part_Bytes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDescriptor_Part_Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor_Part_Bytes.Merge(m, src)
}
func (m *KeyDescriptor_Part_Bytes) XXX_Size() int {
	return m.Size()
}
func (m *KeyDescriptor_Part_Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor_Part_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor_Part_Bytes proto.InternalMessageInfo

func (m *KeyDescriptor_Part_Bytes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyDescriptor_Part_Bytes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *KeyDescriptor_Part_Bytes) GetFixedWidth() uint32 {
	if m != nil {
		return m.FixedWidth
	}
	return 0
}

type KeyDescriptor_Part_String struct {
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *KeyDescriptor_Part_String) Reset()         { *m = KeyDescriptor_Part_String{} }
func (m *KeyDescriptor_Part_String) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor_Part_String) ProtoMessage()    {}
func (*KeyDescriptor_Part_String) Descriptor() ([]byte, []int) {
	return fileDescriptor_335ca074c797b8b4, []int{0, 0, 1}
}
func (m *KeyDescriptor_Part_String) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDescriptor_Part_String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDescriptor_Part_String.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDescriptor_Part_String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor_Part_String.Merge(m, src)
}
func (m *KeyDescriptor_Part_String) XXX_Size() int {
	return m.Size()
}
func (m *KeyDescriptor_Part_String) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor_Part_String.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor_Part_String proto.InternalMessageInfo

func (m *KeyDescriptor_Part_String) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyDescriptor_Part_String) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type KeyDescriptor_Part_Separator struct {
	Separator string `protobuf:"bytes,1,opt,name=separator,proto3" json:"separator,omitempty"`
}

func (m *KeyDescriptor_Part_Separator) Reset()         { *m = KeyDescriptor_Part_Separator{} }
func (m *KeyDescriptor_Part_Separator) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor_Part_Separator) ProtoMessage()    {}
func (*KeyDescriptor_Part_Separator) Descriptor() ([]byte, []int) {
	return fileDescriptor_335ca074c797b8b4, []int{0, 0, 2}
}
func (m *KeyDescriptor_Part_Separator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDescriptor_Part_Separator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDescriptor_Part_Separator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDescriptor_Part_Separator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor_Part_Separator.Merge(m, src)
}
func (m *KeyDescriptor_Part_Separator) XXX_Size() int {
	return m.Size()
}
func (m *KeyDescriptor_Part_Separator) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor_Part_Separator.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor_Part_Separator proto.InternalMessageInfo

func (m *KeyDescriptor_Part_Separator) GetSeparator() string {
	if m != nil {
		return m.Separator
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyDescriptor)(nil), "cosmos_sdk.x.schema.v1.KeyDescriptor")
	proto.RegisterType((*KeyDescriptor_Part)(nil), "cosmos_sdk.x.schema.v1.KeyDescriptor.Part")
	proto.RegisterType((*KeyDescriptor_Part_Bytes)(nil), "cosmos_sdk.x.schema.v1.KeyDescriptor.Part.Bytes")
	proto.RegisterType((*KeyDescriptor_Part_String)(nil), "cosmos_sdk.x.schema.v1.KeyDescriptor.Part.String")
	proto.RegisterType((*KeyDescriptor_Part_Separator)(nil), "cosmos_sdk.x.schema.v1.KeyDescriptor.Part.Separator")
}

func init() { proto.RegisterFile("x/schema/types/types.proto", fileDescriptor_335ca074c797b8b4) }

var fileDescriptor_335ca074c797b8b4 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x4d, 0x4c, 0x13, 0xc9, 0x8d, 0xdd, 0x0c, 0x52, 0x42, 0xd0, 0x18, 0x5c, 0x55, 0xc5, 0x89,
	0xad, 0xae, 0x45, 0x8a, 0x42, 0xa0, 0x1b, 0x89, 0x05, 0xc1, 0x85, 0x25, 0x4d, 0xa6, 0x6d, 0xa8,
	0xe9, 0x84, 0x99, 0x69, 0x4d, 0xfe, 0xc2, 0x0f, 0xf0, 0x77, 0x04, 0x97, 0x5d, 0xba, 0x94, 0xf6,
	0x47, 0x24, 0x33, 0xf1, 0xb5, 0x85, 0xb7, 0x78, 0xed, 0x26, 0xc9, 0x9c, 0xb9, 0xe7, 0xdc, 0x73,
	0x6e, 0xb8, 0xe0, 0x55, 0x21, 0x4f, 0x97, 0xa4, 0x48, 0x42, 0x51, 0x97, 0x84, 0xab, 0x27, 0x2e,
	0x19, 0x15, 0x14, 0xf5, 0x52, 0xca, 0x0b, 0xca, 0xa7, 0x3c, 0x5b, 0xe1, 0x0a, 0xab, 0x32, 0xbc,
	0x1d, 0x3c, 0xfd, 0x69, 0x42, 0x77, 0x4c, 0xea, 0xf7, 0x84, 0xa7, 0x2c, 0x2f, 0x05, 0x65, 0x08,
	0x41, 0x67, 0x9d, 0x14, 0xc4, 0xd5, 0x03, 0xbd, 0x6f, 0xc7, 0xf2, 0x1b, 0x05, 0xe0, 0x64, 0x6d,
	0x45, 0x4e, 0xd7, 0xee, 0x3d, 0x79, 0x75, 0x0a, 0xa1, 0x87, 0x60, 0x72, 0x41, 0x19, 0x71, 0x3b,
	0xf2, 0x4e, 0x1d, 0x50, 0x0f, 0xac, 0x92, 0x91, 0x79, 0x5e, 0xb9, 0x66, 0xa0, 0xf7, 0x1f, 0xc4,
	0xed, 0x09, 0xbd, 0x03, 0xb3, 0x4c, 0x98, 0xe0, 0xae, 0x15, 0x18, 0x7d, 0x67, 0xf8, 0x1c, 0xdf,
	0xee, 0x0e, 0x9f, 0x39, 0xc3, 0x1f, 0x13, 0x26, 0x62, 0x45, 0x44, 0x8f, 0x01, 0xb6, 0xc9, 0xb7,
	0x0d, 0x99, 0x36, 0x21, 0xdd, 0xfb, 0xb2, 0xa9, 0x2d, 0x91, 0x49, 0x5d, 0x12, 0xef, 0x97, 0x01,
	0x9d, 0xa6, 0x1c, 0x45, 0x60, 0xce, 0x6a, 0x41, 0xb8, 0x8c, 0xe3, 0x0c, 0x5f, 0xdd, 0xbd, 0x13,
	0x1e, 0x35, 0xbc, 0x48, 0x8b, 0x95, 0x00, 0x1a, 0x83, 0xc5, 0x05, 0xcb, 0xd7, 0x0b, 0x19, 0xdf,
	0x19, 0x0e, 0x2e, 0x90, 0xfa, 0x24, 0x89, 0x91, 0x16, 0xb7, 0x12, 0x68, 0x02, 0x36, 0x27, 0x65,
	0xc2, 0x12, 0x41, 0x99, 0x6b, 0x48, 0xbd, 0x37, 0x97, 0xe8, 0xfd, 0xe7, 0x46, 0x5a, 0x7c, 0x14,
	0xf2, 0xbe, 0x82, 0x29, 0x4d, 0x5f, 0xf9, 0x0f, 0x9f, 0x80, 0x33, 0xcf, 0x2b, 0x92, 0x4d, 0xbf,
	0xe7, 0x99, 0x58, 0x4a, 0x5b, 0xdd, 0x18, 0x24, 0xf4, 0xb9, 0x41, 0xbc, 0xb7, 0x60, 0xa9, 0x24,
	0xd7, 0x35, 0xf0, 0x9e, 0x81, 0x7d, 0xe3, 0x1c, 0x3d, 0x3a, 0x1d, 0x81, 0xd2, 0x39, 0x02, 0x23,
	0x13, 0x0c, 0xbe, 0x29, 0x46, 0x1f, 0x7e, 0xef, 0x7d, 0x7d, 0xb7, 0xf7, 0xf5, 0xbf, 0x7b, 0x5f,
	0xff, 0x71, 0xf0, 0xb5, 0xdd, 0xc1, 0xd7, 0xfe, 0x1c, 0x7c, 0xed, 0xcb, 0x8b, 0x45, 0x2e, 0x96,
	0x9b, 0x19, 0x4e, 0x69, 0x11, 0xaa, 0xc1, 0xb5, 0xaf, 0x97, 0x3c, 0x5b, 0x85, 0xe7, 0x9b, 0x30,
	0xb3, 0xe4, 0x12, 0xbc, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x22, 0x67, 0x3c, 0x22, 0x03,
	0x00, 0x00,
}

func (m *KeyDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValueType) > 0 {
		i -= len(m.ValueType)
		copy(dAtA[i:], m.ValueType)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValueType)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Parts) > 0 {
		for iNdEx := len(m.Parts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Parts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Prefix) > 0 {
		i -= len(m.Prefix)
		copy(dAtA[i:], m.Prefix)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Prefix)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Store) > 0 {
		i -= len(m.Store)
		copy(dAtA[i:], m.Store)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Store)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyDescriptor_Part) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDescriptor_Part) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *KeyDescriptor_Part_Bytes_) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_Bytes_) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Bytes != nil {
		{
			size, err := m.Bytes.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *KeyDescriptor_Part_String_) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_String_) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.String_ != nil {
		{
			size, err := m.String_.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *KeyDescriptor_Part_Separator_) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_Separator_) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Separator != nil {
		{
			size, err := m.Separator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *KeyDescriptor_Part_Bytes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDescriptor_Part_Bytes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_Bytes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FixedWidth != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FixedWidth))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyDescriptor_Part_String) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDescriptor_Part_String) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_String) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyDescriptor_Part_Separator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDescriptor_Part_Separator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDescriptor_Part_Separator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Separator) > 0 {
		i -= len(m.Separator)
		copy(dAtA[i:], m.Separator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Separator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeyDescriptor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Store)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Prefix)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Parts) > 0 {
		for _, e := range m.Parts {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.ValueType)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *KeyDescriptor_Part) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *KeyDescriptor_Part_Bytes_) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Bytes != nil {
		l = m.Bytes.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *KeyDescriptor_Part_String_) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.String_ != nil {
		l = m.String_.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *KeyDescriptor_Part_Separator_) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Separator != nil {
		l = m.Separator.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *KeyDescriptor_Part_Bytes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FixedWidth != 0 {
		n += 1 + sovTypes(uint64(m.FixedWidth))
	}
	return n
}

func (m *KeyDescriptor_Part_String) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *KeyDescriptor_Part_Separator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Separator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeyDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Store", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Store = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefix", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefix = append(m.Prefix[:0], dAtA[iNdEx:postIndex]...)
			if m.Prefix == nil {
				m.Prefix = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parts = append(m.Parts, &KeyDescriptor_Part{})
			if err := m.Parts[len(m.Parts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValueType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyDescriptor_Part) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Part: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Part: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bytes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KeyDescriptor_Part_Bytes{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &KeyDescriptor_Part_Bytes_{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field String_", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KeyDescriptor_Part_String{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &KeyDescriptor_Part_String_{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Separator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &KeyDescriptor_Part_Separator{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &KeyDescriptor_Part_Separator_{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyDescriptor_Part_Bytes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bytes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bytes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedWidth", wireType)
			}
			m.FixedWidth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FixedWidth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyDescriptor_Part_String) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: String: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: String: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyDescriptor_Part_Separator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Separator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Separator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Separator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Separator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
